/**
 * Maintainable router configuration: intent → capability → tool → data source → UI mode.
 *
 * Match order is the priority: workflow/transactional, then verification/status,
 * then (in the router) validated identifiers, then knowledge.
 */
import { COMPLAINT_FILING_PATTERN, COMPLAINT_TRACKING_PATTERN } from './intents.js';

export const ROUTER_INTENTS = [
  'greeting',
  'about',
  'knowledge',
  'validation',
  'status',
  'verification',
  'eligibility',
  'calculation',
  'comparison',
  'alert',
  'task',
  'workflow_status',
  'document',
  'translation',
  'analysis',
];

export const ROUTE_CONFIG = {
  greeting: {
    intent: 'greeting',
    capability: 'meta',
    tool: null,
    dataSource: null,
    responseType: 'message',
    uiMode: 'chat',
    useRag: false,
    useProbe: false,
    useLive: false,
  },
  about: {
    intent: 'about',
    capability: 'meta',
    tool: null,
    dataSource: null,
    responseType: 'message',
    uiMode: 'chat',
    useRag: false,
    useProbe: false,
    useLive: false,
  },
  knowledge: {
    intent: 'knowledge',
    capability: 'retrieval',
    tool: 'search_knowledge_base',
    dataSource: 'rag_index',
    responseType: 'answer',
    uiMode: 'knowledge',
    useRag: true,
    useProbe: true,
    useLive: true,
  },
  validation: {
    intent: 'validation',
    capability: 'validation_engine',
    tool: 'run_deterministic_rule',
    dataSource: 'rules_engine',
    responseType: 'verification_card',
    uiMode: 'verification',
    useRag: false,
    useProbe: false,
    useLive: false,
    useRulesEngine: true,
  },
  status: {
    intent: 'status',
    capability: 'status_engine',
    tool: 'run_deterministic_rule',
    dataSource: 'rules_engine',
    responseType: 'verification_card',
    uiMode: 'verification',
    useRag: false,
    useProbe: false,
    useLive: false,
    useRulesEngine: true,
    ruleId: 'STATUS-CML-001',
  },
  verification: {
    intent: 'verification',
    capability: 'verification_engine',
    tool: 'run_deterministic_rule',
    dataSource: 'rules_engine',
    responseType: 'verification_card',
    uiMode: 'verification',
    useRag: false,
    useProbe: false,
    useLive: false,
    useRulesEngine: true,
  },
  eligibility: {
    intent: 'eligibility',
    capability: 'eligibility_engine',
    tool: 'run_deterministic_rule',
    dataSource: 'rules_engine',
    responseType: 'verification_card',
    uiMode: 'verification',
    useRag: false,
    useProbe: false,
    useLive: false,
    useRulesEngine: true,
    ruleId: 'VAL-QCO-001',
  },
  calculation: {
    intent: 'calculation',
    capability: 'calculator',
    tool: 'search_marking_fees',
    dataSource: 'clone_rules',
    responseType: 'calculation_card',
    uiMode: 'calculation',
    useRag: false,
    useProbe: true,
    useLive: false,
  },
  comparison: {
    intent: 'comparison',
    capability: 'comparison_engine',
    tool: 'run_deterministic_rule',
    dataSource: 'rules_engine',
    responseType: 'comparison_ui',
    uiMode: 'comparison',
    useRag: false,
    useProbe: false,
    useLive: false,
    useRulesEngine: true,
    ruleId: 'VAL-AMD-001',
  },
  alert: {
    intent: 'alert',
    capability: 'alert_engine',
    tool: 'check_system_freshness',
    dataSource: 'compliance_alerts',
    responseType: 'alert_list',
    uiMode: 'alert',
    useRag: false,
    useProbe: true,
    useLive: false,
  },
  task: {
    intent: 'task',
    capability: 'workflow_engine',
    tool: 'discover_ebis_service',
    dataSource: 'ebis_workflow',
    responseType: 'workflow_ui',
    uiMode: 'workflow',
    useRag: false,
    useProbe: true,
    useLive: false,
    useWorkflowEngine: true,
  },
  workflow_status: {
    intent: 'workflow_status',
    capability: 'workflow_engine',
    tool: 'get_workflow_status',
    dataSource: 'ebis_workflow',
    responseType: 'workflow_ui',
    uiMode: 'workflow',
    useRag: false,
    useProbe: true,
    useLive: false,
    useWorkflowEngine: true,
  },
  document: {
    intent: 'document',
    capability: 'document_engine',
    tool: 'generate_air_template',
    dataSource: 'clone_templates',
    responseType: 'document',
    uiMode: 'document',
    useRag: false,
    useProbe: true,
    useLive: false,
  },
  translation: {
    intent: 'translation',
    capability: 'translation',
    tool: 'get_bilingual_educational_data',
    dataSource: 'bilingual_api',
    responseType: 'answer',
    uiMode: 'knowledge',
    useRag: false,
    useProbe: true,
    useLive: false,
  },
  analysis: {
    intent: 'analysis',
    capability: 'analysis_engine',
    tool: 'derive_formula_limits',
    dataSource: 'rag_index',
    responseType: 'analysis',
    uiMode: 'analysis',
    useRag: true,
    useProbe: true,
    useLive: false,
  },
};

/**
 * Rule patterns — first match wins (after meta rules).
 * Priority: transactional workflow → verification/status → validated identifiers → knowledge.
 */
export const ROUTE_RULES = [
  { intent: 'task', patterns: [COMPLAINT_FILING_PATTERN], tool: 'get_ebis_service', serviceId: 'SVC-GRIEV-001' },
  { intent: 'workflow_status', patterns: [COMPLAINT_TRACKING_PATTERN], tool: 'get_workflow_status' },
  { intent: 'knowledge', patterns: [
    /\b(manufacture\s+induction|induction\s+cooking).*\b(outside\s+india|foreign|export|sell\s+in\s+india)\b/i,
    /\bforeign\s+(manufacturer|exporter|plant).*\b(induction|appliance)\b/i,
  ], tool: 'verify_import_compliance' },
  { intent: 'knowledge', patterns: [
    /\b(find|which|recommend|need\s+to\s+test).*\b(lab|laboratory)\b.*\binduction\b/i,
    /\btest\s+my\s+induction\s+cooking\b/i,
  ], tool: 'suggest_testing_labs' },
  { intent: 'verification', patterns: [
    /\bCML-DEMO-61003\b/i,
    /\bLIC-DEMO-26003\b/i,
    /\bverify\s+CML-DEMO\b/i,
  ], tool: 'verify_registry_id' },
  { intent: 'validation', patterns: [
    /\bHUID-DM26-H29ZC6\b/i,
    /\bverify\s+its\s+huid\b/i,
    /\bHUID-DM26-Z99FLAG\b/i,
  ], tool: 'verify_huid_code' },
  { intent: 'comparison', patterns: [
    /\bSTD-DEMO-010\b/i,
    /\bSTD-DEMO-011\b/i,
    /\bcompare\b.*\b1010\b.*\b1011\b/i,
  ], tool: 'generate_revision_diff' },
  { intent: 'task', patterns: [
    /\blog\s+(a\s+)?(sealed\s+sample|inspection\s+photographs?|evidence)\b.*\bENF-DEMO-\d+\b/i,
    /\bENF-DEMO-\d+\b.*\blog\s+(evidence|sealed\s+sample|photographs?)\b/i,
  ], tool: 'log_raid_evidence' },
  { intent: 'knowledge', patterns: [
    /\bSURV-DEMO-001\b/i,
    /\binspect(ing|ion).*\bhelmet\b/i,
    /\bENF-DEMO-001\b/i,
  ], tool: 'search_enforcement_cases' },
  { intent: 'status', patterns: [
    /\b(is\s+(this|the|my)\s+licen[cs]e\s+active|active\s+licen[cs]e|licen[cs]e\s+status)\b/i,
    /\bCML[\s-]?DEMO[\s-]?[\w]+/i,
    /\b(is\s+)?CML[\s-]?[\d\w-]+\s+active\b/i,
  ], tool: 'run_deterministic_rule', ruleId: 'STATUS-CML-001' },
  { intent: 'validation', patterns: [
    /\b(verify\s+(huid|lab)|validate\s+(huid|lab|standard)|HUID[\s-][A-Z0-9-]+)\b/i,
    /\bLAB[\s-]?ID[\s-]?DEMO/i,
    /\b(does|is)\s+.*\bIS\s+.*\bexist/i,
  ], tool: 'run_deterministic_rule' },
  { intent: 'verification', patterns: [
    /\b(verify\s+(licen[cs]e|cml|registry)|check\s+.*status|registry\s+verify)\b/i,
    /\b(CM\/L|registry\s+verify|verify\s+registry)\b/i,
    /\b(8830112|4151999)/i,
  ], tool: 'run_deterministic_rule', ruleId: 'STATUS-CML-001' },
  { intent: 'eligibility', patterns: [
    /\b(qco\s+appl|does\s+a\s+qco|mandatory\s+under\s+qco|qco\s+apply)\b/i,
    /\bQCO[\s-]?DEMO/i,
  ], tool: 'run_deterministic_rule', ruleId: 'VAL-QCO-001' },
  { intent: 'calculation', patterns: [
    /\b(calculate|compensation|budget|how\s+much\s+(will\s+it\s+cost|kharcha)|fee\s+for|marking\s+fee)\b/i,
    /\b(₹|inr|rupee|carat\s+deficit)\b/i,
  ], tool: 'calculate_gold_compensation' },
  { intent: 'comparison', patterns: [
    /\b(amendments?|revision|amended)\b/i,
    /\b(compare|comparison|difference\s+between|vs\.?|versus|mutated\s+between)\b/i,
    /\b(revision\s+diff|two\s+standards)\b/i,
  ], tool: 'run_deterministic_rule', ruleId: 'VAL-AMD-001' },
  { intent: 'alert', patterns: [
    /\b(my\s+(application\s+)?alerts?|my\s+notifications?|unread\s+alerts?|any\s+updates?\s+on\s+my)\b/i,
  ], tool: 'list_user_alerts' },
  { intent: 'alert', patterns: [
    /\b(today'?s?\s+alerts?|compliance\s+alert|critical\s+alert|show\s+alerts?|unacknowledged)\b/i,
    /\b(what\s+changed\s+overnight|fingerprint)\b/i,
  ], tool: 'check_system_freshness' },
  { intent: 'workflow_status', patterns: [
    /\b(status\s+of|what'?s?\s+the\s+status|track\s+(my|the)|application\s+status|complaint\s+status)\b/i,
    /\b(next\s+step|what\s+happens\s+after|progress\s+of)\b/i,
    /\b(CERT|CMP|LAB-APP|BIS-APP|WF|CON-GRP)[\s-]?DEMO[\s-]?[\w-]+/i,
    /\bBIS-APP-[\w-]+/i,
  ], tool: 'get_workflow_status' },
  { intent: 'knowledge', patterns: [
    /\bindustrial\s+safety\s+helmets?\b.*\b(standard|mandatory|tests?|documents?|requirements?)\b/i,
    /\b(standard|mandatory|tests?|documents?|requirements?)\b.*\bindustrial\s+safety\s+helmets?\b/i,
  ], tool: 'search_standards' },
  { intent: 'task', patterns: [
    /\b(what\s+documents|which\s+documents|required\s+documents|documents\s+do\s+i\s+need)\b/i,
    /\b(what\s+do\s+i\s+need\s+to\s+apply|help\s+me\s+apply|which\s+service|find\s+a\s+bis\s+service)\b/i,
  ], tool: 'get_ebis_service' },
  { intent: 'task', patterns: [
    /\b(apply\s+for\s+certif|certification\s+roadmap|step[\s-]by[\s-]step|how\s+to\s+get\s+certif)\b/i,
    /\b(what\s+do\s+i\s+need\s+for\s+certif|certification\s+requirements)\b/i,
  ], tool: 'get_certification_roadmap', serviceId: 'SVC-CERT-001' },
  { intent: 'task', patterns: [
    /\b(submit\s+(application|form)|fill\s+out|form-?i|ebis)\b/i,
  ], tool: 'submit_portal_form' },
  { intent: 'document', patterns: [
    /\b(generate\s+(template|document|air)|air\s+template)\b/i,
  ], tool: 'generate_air_template' },
  { intent: 'translation', patterns: [
    /\b(translate|hindi|हिन्दी|bilingual|simple\s+hindi)\b/i,
    /\b(jargon|technical\s+term)\b/i,
  ], tool: 'get_bilingual_educational_data' },
  { intent: 'analysis', patterns: [
    /\b(analy[sz]e|derive|formula|mathematical\s+steps|revision\s+diff|engineering\s+table)\b/i,
    /\b(stress-?strain|yield\s+point|semester\s+updates)\b/i,
  ], tool: 'derive_formula_limits' },
  { intent: 'knowledge', patterns: [
    /\b(conformity\s+assessment|surveillance\s+(mode|type|activity)|pro-?active\s+surveillance|re-?active\s+surveillance|dynamic\s+surveillance)\b/i,
  ], tool: 'search_knowledge_base' },
  { intent: 'knowledge', patterns: [
    /\b(IS\s*[\d]|QCO|standard|mandatory|voluntary|helmet|safety|which\s+standard)\b/i,
    /\b(tell\s+me\s+about|what\s+is|explain|apply\s+to)\b/i,
  ], tool: 'search_knowledge_base' },
];
