/** MITRA user personas — demo impersonation drives sidebar, prompts, and context density. */
export const USER_PERSONAS = [
  {
    id: 'industry',
    label: 'Industry Persona',
    short: 'Industry',
    icon: '🏭',
    description: 'Manufacturers, MSMEs, startups, and factory owners — certification, licences, QCO, Form-I.',
    focusAreas: ['Product certification', 'Licence / CML', 'QCO compliance', 'Factory inspection'],
    agentMode: 'industry',
    interests: { is_numbers: ['IS 2082:2018', 'IS 4151:2015', 'IS 623:2025'], sectors: ['Certification', 'Standards', 'QCO'] },
    demoActions: [
      { id: 'publish-amendment', label: 'Trigger: IS 4151 amendment', bisPath: '/demo-console' },
      { id: 'geyser-qco', label: 'Ask: geyser mandatory?', prompt: 'Is geyser certification mandatory under QCO?' },
    ],
  },
  {
    id: 'foreign_exporter',
    label: 'Foreign Exporter',
    short: 'Foreign Exporter',
    icon: '🌐',
    description: 'International manufacturers and importers — FMCS, CRS, export QCO, AIR nomination, MRA treaties.',
    focusAreas: ['FMCS', 'Import clearance', 'Export QCO', 'MRA / test waivers'],
    agentMode: 'industry',
    interests: { is_numbers: ['IS 16046 (Part 2):2018', 'IS 15844:2010', 'IS 13252 (Part 1):2010'], sectors: ['FMCS', 'CRS', 'Export', 'QCO', 'MRA'] },
    demoActions: [
      { id: 'fmcs-border-alert', label: '🚨 Trigger: FMCS border alert', bisPath: '/demo-console' },
      { id: 'fmcs-customs-detention', label: '⚠️ Trigger: Customs detention', bisPath: '/demo-console' },
      { id: 'mra-activated', label: '✅ Trigger: MRA EU test waiver', bisPath: '/demo-console' },
      { id: 'export-qco', label: 'Ask: LED import rules', prompt: 'What QCO applies to LED lamps imported into India? Do we need a BIS license?' },
      { id: 'ask-fmcs', label: 'Ask: ECU import compliance', prompt: 'We are a German automotive plant exporting ECUs to Chennai port. Do we need an FMCS license before shipping?' },
    ],
  },
  {
    id: 'citizen',
    label: 'Everyday Citizen',
    short: 'Citizen',
    icon: '👤',
    description: 'Retail consumers and buyers — safety, complaints, counterfeit checks, hazard alerts.',
    focusAreas: ['File a complaint', 'Verify products', 'Safety guidance', 'Track grievance'],
    agentMode: 'consumer',
    interests: { is_numbers: ['IS 9873 (Part 3):2017', 'IS 2082:2018', 'IS 4151:2015'], sectors: ['Consumer', 'Safety', 'Grievance'] },
    demoActions: [
      { id: 'c1-toys', label: 'C1 · Toy safety IS 9873', prompt: 'I am buying plastic toys for my 3-year-old child. What basic safety tests or toxin limits must a toy clear to get an official BIS safety mark?' },
      { id: 'c2-grievance', label: 'C2 · File extension board complaint', prompt: 'My new extension board caught fire this morning while charging my phone. I have the store bill. Can you file an official complaint against this brand for me?' },
      { id: 'c3-track', label: 'C3 · Track complaint', prompt: 'Has the enforcement team taken any action on the complaint I filed yesterday against the defective extension board brand?' },
      { id: 'c4-jargon', label: 'C4 · Decode heater jargon', prompt: 'My room heater box talks about passing a \'2000V Dielectric High-Voltage Insulation test.\' Can you translate that into plain language for me?' },
      { id: 'c5-dispute', label: 'C5 · Geyser refund dispute', prompt: 'The shopkeeper refuses to refund me for a defective geyser, claiming BIS certification isn\'t mandatory. What legal clause can I show them to prove they are wrong?' },
      { id: 'c6-counterfeit', label: 'C6 · Verify CM/L helmet', prompt: 'I am holding a helmet with a BIS license stamp that says CM/L-4151999. Can you check the live database to tell me if this is a real factory license?' },
      { id: 'c7-hindi', label: 'C7 · Gold rights in Hindi', prompt: 'I am buying a gold ring. Tell me my basic checking rights in simple Hindi language.' },
      { id: 'c8-hazard', label: 'C8 · Flag toxic bottles', prompt: 'This local store is selling cheap unbranded baby feeding bottles that smell intensely like toxic industrial plastic. Flag this as an immediate hazard.' },
      { id: 'live-officer', label: '⚡ Live: Dispatch officer', bisPath: '/demo-console?tab=citizen', actionId: 'grievance-officer-assigned' },
      { id: 'live-toy-ban', label: '🚨 Live: Toxic toy ban', bisPath: '/demo-console?tab=citizen', actionId: 'toy-safety-ban' },
      { id: 'live-seizure', label: '🛑 Live: Counterfeit seizure', bisPath: '/demo-console?tab=citizen', actionId: 'counterfeit-helmet-seizure' },
      { id: 'live-hazard', label: '🍼 Live: Hazard escalation', bisPath: '/demo-console?tab=citizen', actionId: 'hazard-bottle-alert' },
    ],
  },
  {
    id: 'gold_investor',
    label: 'Gold Buyer & Investor',
    short: 'Gold Buyer',
    icon: '💍',
    description: 'Jewellery consumers and investors — hallmarking, HUID verification, purity complaints.',
    focusAreas: ['HUID verification', 'Hallmarking', 'Purity disputes', 'Consumer rights'],
    agentMode: 'consumer',
    interests: { is_numbers: [], sectors: ['Hallmarking'] },
    demoActions: [
      { id: 'g1-stamp', label: 'G1 · Decode 22K916 stamp', prompt: 'I am looking at a gold bangle stamped with 22K916 and a little triangle. What does this mean, and how pure is the gold?' },
      { id: 'g2-huid', label: 'G2 · Verify HUID A1B2C3', prompt: 'I have a necklace with the HUID code A1B2C3. Can you verify its tracking status and tell me when it was stamped?' },
      { id: 'g3-violation', label: 'G3 · Report unhallmarked sales', prompt: 'This jeweler in the local market is selling gold chains without any HUID or hallmark stamps. I want to report them immediately.' },
      { id: 'g4-compensation', label: 'G4 · Carat deficit compensation', prompt: 'My store receipt says 22K (91.6%), but my lab test report shows it is actually only 18K (75.0%). The necklace weighs 20 grams, and I paid ₹1,40,000. How much compensation must the jeweler legally pay me?' },
      { id: 'live-hallmark', label: '💍 Live: Hallmarking expansion', bisPath: '/demo-console?tab=hallmarking', actionId: 'hallmarking-expansion' },
    ],
  },
  {
    id: 'lab_testing',
    label: 'Testing Infrastructure',
    short: 'Laboratory',
    icon: '🔬',
    description: 'Laboratory owners, managers, and test technicians — recognition, scope, NABL, validation.',
    focusAreas: ['Lab recognition', 'Test scope', 'NABL alignment', 'Sample validation'],
    agentMode: 'industry',
    interests: { is_numbers: ['IS 4151:2015', 'IS 2082:2018'], sectors: ['Labs', 'Standards'] },
    demoActions: [
      { id: 'l1-env', label: 'L1 · IS 1786 room limits', prompt: 'What are the mandatory room temperature and humidity limits our lab must maintain while running mechanical stress tests on steel bars under IS 1786?' },
      { id: 'l2-cert', label: 'L2 · Log test certificate S-992', prompt: 'I have finished the test run for Sample ID #S-992. The tensile strength cleared at 550 MPa. Log this report to the central registry.' },
      { id: 'l3-validation', label: 'L3 · Bulk upload failure', prompt: 'Why did my last bulk data upload fail validation bounds?' },
      { id: 'l4-blind', label: 'L4 · Blind cross-testing BLIND-X1', prompt: 'Initialize a new blind cross-testing workflow for concrete cube baseline sample batch #BLIND-X1 across our three competing regional labs.' },
      { id: 'live-lab', label: '🔬 Live: Lab validation alert', bisPath: '/demo-console?tab=labs', actionId: 'lab-validation-fail' },
    ],
  },
  {
    id: 'enforcement',
    label: 'Enforcement Officer',
    short: 'Enforcement Officer',
    icon: '🛃',
    description: 'Customs agents, border inspectors, and government auditors — cases, seizures, mandatory lists.',
    focusAreas: ['Enforcement cases', 'Licence verification', 'HS code clearance', 'Seizure orders'],
    agentMode: 'industry',
    interests: { is_numbers: ['IS 4151:2015', 'IS 2062:2011'], sectors: ['QCO', 'Standards', 'Enforcement'] },
    demoActions: [
      { id: 'e1-evidence', label: 'E1 · Log raid evidence', prompt: 'I am inside a rogue factory floor. Log an active evidence entry for 500 boxes of uncertified cement bags branded with a fake ISI logo.' },
      { id: 'e2-license', label: 'E2 · Verify CM/L-8830112', prompt: 'Run a quick background check on factory license number CM/L-8830112 to see if it is currently active or suspended.' },
      { id: 'e3-hs', label: 'E3 · HS 8504.40.90 clearance', prompt: 'An incoming cargo container at the port lists product HS Code 8504.40.90. Does this require immediate BIS clearance before passing customs?' },
      { id: 'e4-seal', label: 'E4 · Emergency factory seal', prompt: 'Raid site non-compliance confirmed at factory CM/L-8830112. Execute an immediate emergency factory-sealing order and bypass standard administrative queues.' },
      { id: 'live-seal', label: '🛃 Live: Emergency seal order', bisPath: '/demo-console?tab=amendment', actionId: 'enforcement-emergency-seal' },
    ],
  },
  {
    id: 'academic',
    label: 'Academic Researcher',
    short: 'Researcher',
    icon: '🎓',
    description: 'Engineering, science, and policy students — standards development, IS history, technical clauses.',
    focusAreas: ['Standards research', 'Revision history', 'Technical clauses', 'Gazette tracking'],
    agentMode: 'industry',
    interests: { is_numbers: ['IS 4151:2015', 'IS 623:2025', 'IS 2082:2018'], sectors: ['Standards', 'Policy', 'Research'] },
    demoActions: [
      { id: 'a1-table', label: 'A1 · IS 2062 full table', prompt: 'Show me the full, un-truncated material stress-strain limit values and yield points for structural steel under IS 2062.' },
      { id: 'a2-semester', label: 'A2 · Semester gazette tracker', prompt: 'List all new gazette notifications or standard revisions published during the current academic semester.' },
      { id: 'a3-formula', label: 'A3 · Insulation formula derivation', prompt: 'What are the exact mathematical steps and variables used to derive the breakdown threshold limits for high-voltage insulation tests?' },
      { id: 'a4-diff', label: 'A4 · IS 4151 revision diff', prompt: 'Generate a structural diff matrix comparing how the helmet impact velocity safety rules mutated between the 1993 version and the 2018 version of IS 4151.' },
      { id: 'live-gazette', label: '🎓 Live: Semester publication', bisPath: '/demo-console?tab=amendment', actionId: 'academic-semester-update' },
    ],
  },
];

export function getPersona(id) {
  return USER_PERSONAS.find(p => p.id === id) || USER_PERSONAS[0];
}
